"""Content schedule rule model for recurring content automation."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import Field

from app.models.base import MongoBaseModel
from app.models.scheduled_content import ContentPlatform, ContentType


class RuleFrequency(str, Enum):
    """Frequency of rule execution."""

    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"


class ContentCategory(str, Enum):
    """Category of content to generate."""

    MOTIVATIONAL = "motivational"  # Motywacyjne
    INDUSTRY_NEWS = "industry_news"  # Branżowe newsy
    EDUCATIONAL = "educational"  # Edukacyjne
    PROMOTIONAL = "promotional"  # Promocyjne
    BEHIND_SCENES = "behind_scenes"  # Za kulisami
    SEASONAL = "seasonal"  # Okolicznościowe
    CUSTOM = "custom"  # Custom prompt


class ApprovalMode(str, Enum):
    """How content should be approved before publishing."""

    AUTO_PUBLISH = "auto_publish"  # Full autonomy - publish without asking
    REQUIRE_APPROVAL = "require_approval"  # Notify and wait for approval
    DRAFT_ONLY = "draft_only"  # Only generate to queue, user decides


class ScheduleConfig(MongoBaseModel):
    """Configuration for when to execute the rule."""

    frequency: RuleFrequency = RuleFrequency.WEEKLY
    days_of_week: list[int] = Field(
        default_factory=lambda: [0],  # Monday by default
        description="Days of week (0=Monday, 6=Sunday)",
    )
    day_of_month: int | None = Field(
        None,
        ge=1,
        le=31,
        description="Day of month for monthly frequency",
    )
    time: str = Field(
        "08:00",
        description="Time to generate/publish (HH:MM format)",
    )
    timezone: str = Field(
        "Europe/Warsaw",
        description="Timezone for scheduling",
    )


class ContentTemplate(MongoBaseModel):
    """Template for content generation."""

    category: ContentCategory = ContentCategory.CUSTOM
    prompt_template: str = Field(
        "",
        description="Prompt template with {placeholders}",
    )
    style: str = Field(
        "profesjonalny",
        description="Style/tone of content",
    )
    include_hashtags: bool = Field(
        True,
        description="Whether to include hashtags",
    )
    include_emoji: bool = Field(
        True,
        description="Whether to include emojis",
    )
    generate_image: bool = Field(
        False,
        description="Whether to generate image with AI",
    )
    additional_instructions: str = Field(
        "",
        description="Additional instructions for AI",
    )


class ContentScheduleRule(MongoBaseModel):
    """Rule for automatic content generation and scheduling."""

    # Identification
    company_id: str
    created_by: str  # user_id

    # Rule definition
    name: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Name of the rule",
    )
    description: str | None = Field(
        None,
        max_length=500,
        description="Description of what this rule does",
    )

    # What to generate
    content_type: ContentType = ContentType.INSTAGRAM_POST
    platform: ContentPlatform = ContentPlatform.INSTAGRAM
    content_template: ContentTemplate = Field(
        default_factory=ContentTemplate,
        description="Template configuration for content generation",
    )

    # When to generate
    schedule: ScheduleConfig = Field(
        default_factory=ScheduleConfig,
        description="Schedule configuration",
    )

    # Approval behavior
    approval_mode: ApprovalMode = ApprovalMode.REQUIRE_APPROVAL
    notify_before_publish: bool = Field(
        True,
        description="Whether to notify before auto-publishing",
    )
    notification_minutes: int = Field(
        60,
        ge=5,
        le=1440,
        description="Minutes before publish to notify",
    )
    fallback_on_no_response: str = Field(
        "publish",
        description="What to do if user doesn't respond: 'publish' or 'skip'",
    )

    # Status
    is_active: bool = Field(
        True,
        description="Whether the rule is active",
    )
    last_executed: datetime | None = Field(
        None,
        description="When the rule was last executed",
    )
    next_execution: datetime | None = Field(
        None,
        description="When the rule will next execute",
    )
    last_error: str | None = Field(
        None,
        description="Last error message if any",
    )

    # Limits
    max_queue_size: int = Field(
        4,
        ge=1,
        le=20,
        description="Maximum content items in queue from this rule",
    )

    # Statistics
    total_generated: int = Field(
        0,
        ge=0,
        description="Total content items generated by this rule",
    )
    total_published: int = Field(
        0,
        ge=0,
        description="Total content items published from this rule",
    )


# Default prompt templates for each category
DEFAULT_PROMPTS: dict[ContentCategory, str] = {
    ContentCategory.MOTIVATIONAL: """Stwórz motywacyjny post dla firmy {company_name} z branży {industry}.
Post powinien być inspirujący i zachęcający do działania.
Ton: {style}
{additional_instructions}""",

    ContentCategory.INDUSTRY_NEWS: """Stwórz post o aktualnych trendach i nowościach w branży {industry} dla firmy {company_name}.
Post powinien być informacyjny i pokazywać eksperckość firmy.
Ton: {style}
{additional_instructions}""",

    ContentCategory.EDUCATIONAL: """Stwórz edukacyjny post z poradą lub tipem związanym z {industry} dla firmy {company_name}.
Post powinien dostarczać wartość i budować zaufanie.
Ton: {style}
{additional_instructions}""",

    ContentCategory.PROMOTIONAL: """Stwórz promocyjny post dla firmy {company_name}.
Post powinien zachęcać do skorzystania z oferty, ale nie być nachalny.
Ton: {style}
{additional_instructions}""",

    ContentCategory.BEHIND_SCENES: """Stwórz post "za kulisami" dla firmy {company_name} z branży {industry}.
Post powinien pokazywać ludzką stronę firmy i budować relację z odbiorcami.
Ton: {style}
{additional_instructions}""",

    ContentCategory.SEASONAL: """Stwórz post okolicznościowy (nawiązujący do obecnej pory roku/świąt) dla firmy {company_name} z branży {industry}.
Post powinien być aktualny i angażujący.
Ton: {style}
{additional_instructions}""",

    ContentCategory.CUSTOM: """{prompt_template}
Ton: {style}
{additional_instructions}""",
}
