"""Agent tools module - external capabilities for AI agents."""

from app.services.agents.tools.web_search import (
    TavilySearchTool,
    TavilyTrendsTool,
    TavilyCompetitorTool,
    TavilyMarketDataTool,
    get_tavily_tool,
    get_marketing_tools,
    get_finance_tools,
)
from app.services.agents.tools.pdf_generator import PDFGenerator, pdf_generator
from app.services.agents.tools.image_generator import (
    ImageGeneratorTool,
    SocialMediaImageTool,
    ImageService,
    image_service,
    get_image_tools,
)
from app.services.agents.tools.calculator import (
    VATCalculatorTool,
    MarginCalculatorTool,
    PercentageCalculatorTool,
    CashflowCalculatorTool,
    GeneralCalculatorTool,
    get_calculator_tools,
    get_finance_calculator_tools,
    get_vat_calculator,
    vat_calculator,
    margin_calculator,
    percentage_calculator,
    cashflow_calculator,
    general_calculator,
)
from app.services.agents.tools.validators import (
    UniversalValidatorTool,
    NIPValidatorTool,
    REGONValidatorTool,
    IBANValidatorTool,
    PESELValidatorTool,
    EmailValidatorTool,
    PhoneValidatorTool,
    get_validator_tools,
    get_business_validators,
    get_contact_validators,
    universal_validator,
    nip_validator,
    regon_validator,
    iban_validator,
    pesel_validator,
    email_validator,
    phone_validator,
)

__all__ = [
    # Web Search
    "TavilySearchTool",
    "TavilyTrendsTool",
    "TavilyCompetitorTool",
    "TavilyMarketDataTool",
    "get_tavily_tool",
    "get_marketing_tools",
    "get_finance_tools",
    # PDF
    "PDFGenerator",
    "pdf_generator",
    # Image
    "ImageGeneratorTool",
    "SocialMediaImageTool",
    "ImageService",
    "image_service",
    "get_image_tools",
    # Calculator
    "VATCalculatorTool",
    "MarginCalculatorTool",
    "PercentageCalculatorTool",
    "CashflowCalculatorTool",
    "GeneralCalculatorTool",
    "get_calculator_tools",
    "get_finance_calculator_tools",
    "get_vat_calculator",
    "vat_calculator",
    "margin_calculator",
    "percentage_calculator",
    "cashflow_calculator",
    "general_calculator",
    # Validators
    "UniversalValidatorTool",
    "NIPValidatorTool",
    "REGONValidatorTool",
    "IBANValidatorTool",
    "PESELValidatorTool",
    "EmailValidatorTool",
    "PhoneValidatorTool",
    "get_validator_tools",
    "get_business_validators",
    "get_contact_validators",
    "universal_validator",
    "nip_validator",
    "regon_validator",
    "iban_validator",
    "pesel_validator",
    "email_validator",
    "phone_validator",
]
